### ISSUE TITLE
Cant download package

### ISSUE THREAD

**Issue by LINQeee** [ramirezd42/vst-js#32]
I use windows, after I've installed cmake, boost and vst3 I receive error
`npm ERR! code 1
npm ERR! path D:\Projects\recordtest\node_modules\vstjs
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c cmake-js compile
npm ERR! fs.js:43
npm ERR! } = primordials;
npm ERR!     ^
npm ERR!
npm ERR! ReferenceError: primordials is not defined
npm ERR!     at fs.js:43:5
npm ERR!     at req_ (D:\Projects\recordtest\node_modules\natives\index.js:143:24)
npm ERR!     at Object.req [as require] (D:\Projects\recordtest\node_modules\natives\index.js:55:10)
npm ERR!     at Object.<anonymous> (D:\Projects\recordtest\node_modules\unzip\node_modules\graceful-fs\fs.js:1:37)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1376:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1207:32)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:1023:12)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1235:19)
npm ERR!     at require (node:internal/modules/helpers:176:18)
npm ERR!     at Object.<anonymous> (D:\Projects\recordtest\node_modules\unzip\node_modules\graceful-fs\graceful-fs.js:3:27)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1376:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1207:32)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:1023:12)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1235:19)
npm ERR!
npm ERR! Node.js v20.10.0`

**Comment by LINQeee** [comment]
add `
    "resolutions": {
      "graceful-fs": "^4.2.11"
  }` to package.json
